server:
  port: 8771

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: product-service
  zipkin:
      base-url: http://139.199.122.209:9411
